### ISSUE TITLE
DB error: Multiple primary key defined

### ISSUE THREAD

**Issue by ihorvorotnov** [stuttter/wp-term-meta#4]
On activation and after that on every admin page load there's an `ALTER TABLE wp_termmeta ADD PRIMARY KEY (meta_id)` SQL trying to run, and it fails with error `Multiple primary key defined`.

Here's the debug.log output:

`[02-Sep-2015 23:45:55 UTC] WordPress database error Multiple primary key defined for query ALTER TABLE wp_termmeta ADD PRIMARY KEY (meta_id) made by do_action('admin_init'), call_user_func_array, WP_Term_Meta->admin_init, WP_Term_Meta->maybe_upgrade_database, WP_Term_Meta->upgrade_database, WP_Term_Meta->create_termmeta_table, dbDelta, QM_DB->query
`

Here's the screen from Query Monitor:

![wp-term-meta-error](https://cloud.githubusercontent.com/assets/1066083/9647552/ec42c7da-51e6-11e5-9a6c-dedea58022da.png)

Clean install of WordPress 4.3, WP Term Meta 0.1.2.
Just in case, dev environment is Win10 x64, Nginx 1.9, PHP 5.6, MariaDB 10

**Comment by johnjamesjacoby** [comment]
Term meta is in WordPress 4.4, so closing this.
