### ISSUE TITLE
Issue with cached get_term() response

### ISSUE THREAD

**Issue by richardsweeney** [stuttter/wp-term-meta#5]
If you call get_terms() twice on the same page, the first result of the query is returned for both queries. This is because the first term query is cached by WP and is subsequently returned by the second query as both queries produce the same cache key.

The first query is a simple get_terms() without meta_data but the second query used a filter via meta_query. For the second query the same set of results was returned as the first query, but if I remove the first query the results for the second query (with meta paramaters works as expected).

Example:

```php
// First call:
$terms = get_terms( 'cool_cat', [ 'hide_empty' => false ] );
// Yup

// Second call:
$terms = get_terms( 'cool_cat', [
    'hide_empty' => false,
    'meta_query' => [
        [
            'key'     => 'color',
            'value'   => '#c1272c',
            'compare' => '=',
        ]
    ]
] );
// Nope, get the same results as the first query.
```

I can confirm that the same cache key is generated for both queries.

**Comment by johnjamesjacoby** [comment]
See #2 and also:

https://make.wordpress.org/core/2015/09/22/preparing-your-plugins-and-your-client-sites-for-termmeta/

**Comment by johnjamesjacoby** [comment]
Term meta is in WordPress 4.4, so closing this.
